import { Geist, Geist_Mono ,Roboto,Red_Hat_Display } from "next/font/google";
// import 'bootstrap/dist/css/bootstrap.min.css';
import "./globals.css";
import AOSInit from "@/components/Common/AOSInit";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const redHatDisplay = Red_Hat_Display({
  subsets: ['latin'],
  weight: ['400', '500', '700'], // Choose weights you need
  display: 'swap',
});
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const roboto = Roboto({
  subsets: ['latin'],
  display: 'swap',
})

export const metadata = {
  title: "Deep Conversation",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.png", // You can also use PNG or SVG: "/favicon.png"
  },
};


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${redHatDisplay.className} ${geistMono.variable} ${roboto.className} antialiased`}
      >
        <AOSInit />
        {children}
      </body>
    </html>
  );
}
